---
# tasks file for common
- name: Hello World Sample
  debug:
    msg: "Hello World!"

- name: Run Python Script
  command:
    argv:
      - python3
      - common/files/main.py
  register: output

- name: Debug Python script output
  debug:
    var: output.stdout_lines
